import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My Company Landing Page",
  description: "Generated by create next app",
  keywords: "landing page, my company, filesure assignment, filesure internship assignment",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" href="/logo.png" type="image/x-icon" />
        <link rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Crimson+Pro"></link>
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
